#!/usr/bin/env python3
"""
Regenerate FILE-INDEX.md from manifest.json, and report any drift between the
manifest and what is actually on disk.

Usage:
    python3 scripts/build_index.py

Exits non-zero if drift is found (missing files, missing thumbs, or orphaned
images that no project references), so it can be used as a pre-commit check.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "manifest.json"
INDEX = ROOT / "FILE-INDEX.md"

m = json.loads(MANIFEST.read_text())
cats = {c["id"]: c for c in m["categories"]}
image_root, thumb_root = m["imageRoot"], m["thumbRoot"]
thumb_ext = m.get("thumbExt", ".webp")

problems = []
referenced = set()
lines = [
    "# File Index",
    "",
    "Auto-generated by `scripts/build_index.py`. Do not edit by hand.",
    "`manifest.json` is the source of truth — this file is a readable mirror of it.",
    "",
]

total = 0
for cat in sorted(m["categories"], key=lambda c: c["order"]):
    projects = sorted(
        (p for p in m["projects"] if p["category"] == cat["id"]),
        key=lambda p: (p.get("order", 999), p["id"]),
    )
    lines += [f"## {cat['title']}", "", f"`{image_root}/{cat['dir']}/`", ""]

    if not projects:
        lines += ["_No work added yet._", ""]
        continue

    for p in projects:
        lines.append(f"### {p['title']}  \n`id: {p['id']}`")
        lines.append("")
        if p.get("url"):
            lines.append(f"- live site: <{p['url']}>")
            if p.get("blurb"):
                lines.append(f"  — {p['blurb']}")
        for fn in p["images"]:
            src = ROOT / image_root / cat["dir"] / fn
            thb = (ROOT / thumb_root / cat["dir"] / fn).with_suffix(thumb_ext)
            referenced.add(src.resolve())
            total += 1
            flags = []
            if fn == p.get("cover"):
                flags.append("cover")
            if not src.exists():
                flags.append("**MISSING**")
                problems.append(f"missing image: {image_root}/{cat['dir']}/{fn}")
            if not thb.exists():
                flags.append("**NO THUMB**")
                problems.append(f"missing thumb: {thb.relative_to(ROOT)}")
            suffix = f"  — {', '.join(flags)}" if flags else ""
            lines.append(f"- `{fn}`{suffix}")
        lines.append("")

for f in sorted((ROOT / image_root).rglob("*.png")):
    if f.resolve() not in referenced:
        problems.append(f"orphan (on disk, not in manifest): {f.relative_to(ROOT)}")

lines += ["---", "", f"**{total}** images across **{len(m['projects'])}** projects.", ""]
if problems:
    lines += ["### Drift detected", ""] + [f"- {p}" for p in problems] + [""]

INDEX.write_text("\n".join(lines))
print(f"Wrote {INDEX.relative_to(ROOT)} — {total} images, {len(m['projects'])} projects.")
for p in problems:
    print(f"  ! {p}")

raise SystemExit(1 if problems else 0)
